apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: orderhub
spec:
  selector:
    app: backend
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: orderhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/alejo11102001/orderhub-backend:sha-4f8f1f6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/orderhub
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderhub-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orderhub-secrets
                  key: JWT_SECRET
            - name: APP_DEMO_DATA
              value: "false"   # "true" crea productos de demostración (idempotente)
            - name: APP_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: orderhub-secrets
                  key: APP_ADMIN_EMAIL
                  optional: true
            - name: APP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orderhub-secrets
                  key: APP_ADMIN_PASSWORD
                  optional: true
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              memory: 384Mi
              cpu: 100m
            limits:
              memory: 768Mi